version: '3.8'
services:

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: clientes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cliente_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  cliente-service:
    build:
      context: . # ← Altere conforme necessário
    container_name: cliente-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      - db
      - rabbitmq

volumes:
  cliente_postgres_data:
