server:
  port: 8081
  servlet:
    context-path: /clientes

spring:
  application:
    name: cliente-service

  datasource:
    url: jdbc:postgresql://db:5432/clientes_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    org.springframework: INFO
    com.fiap.rm358568.edusocrates: DEBUG
